# @format

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone git
        uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"
      - name: build wasm-project
        run: wasm-pack build canvas-rs
      - name: install yarn
        run: |
          cd canvas-front
          npm install
          npm run build
          cd ..
          cd canvas-image-rs
          yarn install
          rm -rf ./dist
          yarn build
          cd ..
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: canvas-image-rs/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
