# @format

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone git
        uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install wasm
        run: |
          cargo install wasm-pack
          wasm-pack build canvas-rs
      - name: install yarn
        run: |
          cd canvas-front
          npm install
          npm run build
          cd ..
          cd canvas-image-rs
          yarn install
          yarn build
          cd ..
      - name: use-git
        run: |
          git config --global user.email "rustwasm@rustedu.com"
          git config --global user.name "gh-pages"
          git subtree push --prefix ./canvas-image-rs/dist origin gh-pages
